Filtered format: Fix Uncaught TypeError: fixedValues.split is not a function
Chrome 51+ and Firefox 48+ support the Array.prototype.values()
method, which clashes with the 'values' parameter of the value filter.

See https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/values